# Generated by Django 5.2 on 2025-04-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='nome',
            field=models.CharField(default='sem nome', max_length=50),
            preserve_default=False,
        ),
    ]
