# Generated by Django 5.2 on 2025-04-25 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_academia_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='unidade',
            new_name='academia',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='unidade',
            new_name='academia',
        ),
    ]
